services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen persistente para los datos de MySQL


  backend:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app/back
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app/vuetify-project
      - /app/node_modules
    command: npm run dev

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
